%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-moveit-calibration-gui
Version:        0.1.0
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS moveit_calibration_gui package

License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-cv-bridge
Requires:       ros-noetic-geometric-shapes
Requires:       ros-noetic-moveit-calibration-plugins
Requires:       ros-noetic-moveit-core
Requires:       ros-noetic-moveit-ros-perception
Requires:       ros-noetic-moveit-ros-planning
Requires:       ros-noetic-moveit-ros-planning-interface
Requires:       ros-noetic-moveit-ros-visualization
Requires:       ros-noetic-moveit-visual-tools
Requires:       ros-noetic-pluginlib >= 1.11.2
Requires:       ros-noetic-rosconsole
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-rviz
Requires:       ros-noetic-rviz-visual-tools
Requires:       ros-noetic-tf2-eigen
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-class-loader
BuildRequires:  ros-noetic-cv-bridge
BuildRequires:  ros-noetic-geometric-shapes
BuildRequires:  ros-noetic-image-geometry
BuildRequires:  ros-noetic-moveit-calibration-plugins
BuildRequires:  ros-noetic-moveit-core
BuildRequires:  ros-noetic-moveit-ros-perception
BuildRequires:  ros-noetic-moveit-ros-planning
BuildRequires:  ros-noetic-moveit-ros-planning-interface
BuildRequires:  ros-noetic-moveit-ros-visualization
BuildRequires:  ros-noetic-moveit-visual-tools
BuildRequires:  ros-noetic-pluginlib >= 1.11.2
BuildRequires:  ros-noetic-rosconsole
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-rviz
BuildRequires:  ros-noetic-rviz-visual-tools
BuildRequires:  ros-noetic-tf2-eigen
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
MoveIt calibration gui

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Jun 18 2021 Yu Yan <yu.yan@intel.com> - 0.1.0-3
- Autogenerated by Bloom

* Fri Jun 18 2021 Yu Yan <yu.yan@intel.com> - 0.1.0-2
- Autogenerated by Bloom

* Wed May 12 2021 Yu Yan <yu.yan@intel.com> - 0.1.0-1
- Autogenerated by Bloom

